domain_path: /home/gtaylor/git/opl3_fpga/vitis_sw_project/opl3_hw_platform/export/opl3_hw_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
